export const arrArticles = [{ url: "http://motherboard.vice.com/read/police-grade-mobile-spyware-is-spreading-through-saudi-arabia-and-beyond",
  title: "Police-Grade Mobile Spyware Is Spreading Through Saudi Arabia (and Beyond)",
  author: "THOMAS FOX-BREWSTER",
  position: "CONTRIBUTOR, UK",
  date: "June 24, 2014 // 12:40 PM EST" },
{ url: "http://motherboard.vice.com/read/hacking-teams-equipment-got-stolen-in-panama",
 title: "Hacking Team's Equipment Got Stolen in Panama",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "July 7, 2015 // 07:47 AM EST" },
{ url: "http://motherboard.vice.com/read/here-are-all-the-sketchy-government-agencies-buying-hacking-teams-spy-tech",
  tags: ["essential"],
 title: "Here Are All the Sketchy Government Agencies Buying Hacking Team's Spy Tech",
 author: "JOSHUA KOPSTEIN",
 position: "CONTRIBUTOR",
 date: "July 6, 2015 // 04:08 PM EST" },
{ url: "http://motherboard.vice.com/read/hacking-team-asks-customers-to-stop-using-its-software-after-hack",
 title: "Hacking Team Asks Customers to Stop Using Its Software After Hack",
 tags: ["essential"],
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "July 6, 2015 // 01:55 PM EST" },
{ url: "http://motherboard.vice.com/read/hacker-claims-responsibility-for-the-hit-on-hacking-team",
 title: "Hacker Claims Responsibility for the Hit on Hacking Team",
 tags: ["essential"],
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "July 6, 2015 // 10:21 AM EST" },
{ url: "http://motherboard.vice.com/read/big-banks-worked-with-hacking-team-which-also-sells-spy-tools-to-dictators",
 title: "Big Banks Worked with Hacking Team, Which Also Sells Spy Tools to Dictators ",
 author: "JOSEPH COX",
 position: "CONTRIBUTOR",
 date: "July 6, 2015 // 09:30 AM EST" },
{ url: "http://motherboard.vice.com/read/spy-tech-company-hacking-team-gets-hacked",
 title: "Spy Tech Company 'Hacking Team' Gets Hacked",
 tags: ["essential"],
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "July 5, 2015 // 10:02 PM EST" },
{ url: "http://motherboard.vice.com/read/hacking-team-founder-hey-fbi-we-can-help-you-crack-the-dark-web",
 title: "Hacking Team Founder: Hey FBI, We Can Help You Crack the Dark Web",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "June 2, 2015 // 02:00 PM EST" },
{ url: "http://motherboard.vice.com/read/the-dea-is-coming-under-congressional-scrutiny-for-buying-hacking-tools",
 title: "The DEA Is Coming Under Congressional Scrutiny for Buying Hacking Tools",
 tags: ["essential"],
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "May 1, 2015 // 05:27 PM EST" },
{ url: "http://motherboard.vice.com/read/the-dea-has-been-secretly-buying-hacking-tools-from-an-italian-company",
 title: "The DEA Has Been Secretly Buying Hacking Tools From an Italian Company ",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "April 15, 2015 // 02:00 PM EST" },
{ url: "http://motherboard.vice.com/read/ethiopia-allegedly-used-spyware-against-us-based-journalists-again",
 title: "Ethiopia Allegedly Used Spyware Against US-Based Journalists (Again) ",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "March 9, 2015 // 05:00 AM EST" },
{ url: "http://motherboard.vice.com/read/hacking-team-we-dont-do-business-with-north-korea",
 title: "Hacking Team: 'We Don’t Do Business With North Korea'",
 author: "MARI BASTASHEVSKI",
 position: "CONTRIBUTOR",
 date: "July 11, 2015 // 04:01 AM EST" },
{ url: "http://motherboard.vice.com/read/we-met-with-hacking-team-in-milan",
  tags: ["essential"],
 title: "We Met With Hacking Team in Milan",
 author: "MARI BASTASHEVSKI",
 position: "CONTRIBUTOR",
 date: "July 11, 2015 // 04:00 AM EST" },
{ url: "http://motherboard.vice.com/read/hacking-teams-spyware-targeted-porn-sites-visitors",
 title: "Hacking Team's Spyware Targeted Porn Sites' Visitors",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "July 10, 2015 // 11:30 AM EST" },
{ url: "http://motherboard.vice.com/read/meet-the-companies-that-helped-hacking-team-sell-tools-to-repressive-governments",
  tags: ["essential"],
 title: "Meet the Companies that Helped Hacking Team Sell Tools to Repressive Governments",
 author: "JOSHUA KOPSTEIN",
 position: "CONTRIBUTOR",
 date: "July 10, 2015 // 11:30 AM EST" },
{ url: "http://motherboard.vice.com/read/hacking-team-in-numbers",
  tags: ["essential"],
 title: "Hacking Team by the Numbers",
 author: "JOSEPH COX",
 position: "CONTRIBUTOR",
 date: "July 8, 2015 // 01:45 PM EST" },
{ url: "http://motherboard.vice.com/read/hacking-team-terrorists-can-now-use-our-leaked-spyware",
 title: "Hacking Team: 'Terrorists' Can Now Use Our Leaked Spyware",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "July 8, 2015 // 11:55 AM EST" },
{ url: "http://motherboard.vice.com/read/hacking-team-the-hack-on-us-was-not-done-by-some-random-guy",
 title: "Hacking Team: the Hack on Us Was Not Done by 'Some Random Guy'",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "July 7, 2015 // 04:42 PM EST" },
{ url: "http://motherboard.vice.com/read/hacking-teams-tools-arent-that-impressive-experts-say",
 title: "Hacking Team's Tools Aren't That Impressive, Experts Say",
 author: "JOSEPH COX",
 position: "CONTRIBUTOR",
 date: "July 7, 2015 // 04:00 PM EST" },
{ url: "http://motherboard.vice.com/read/hacking-team-had-ties-to-local-police-departments-across-the-us",
 title: "Hacking Team Had Ties to Local Police Departments Across the US ",
 author: "SHAWN MUSGRAVE",
 position: "CONTRIBUTOR",
 date: "July 24, 2015 // 01:00 PM EST" },
{ url: "http://motherboard.vice.com/read/hacking-team-hey-were-the-victims-here",
 title: "Hacking Team: Hey, We're The Victims Here!",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "July 22, 2015 // 09:59 AM EST" },
{ url: "http://motherboard.vice.com/read/hacking-teams-customers-still-cant-spy-two-weeks-after-hack",
 title: "Hacking Team's Customers Still Can't Spy Two Weeks After Hack",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "July 22, 2015 // 04:00 AM EST" },
{ url: "http://motherboard.vice.com/read/the-dea-just-cancelled-its-contract-with-hacking-team",
 title: "The DEA Just Cancelled Its Contract With Hacking Team",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "July 17, 2015 // 03:58 PM EST" },
{ url: "http://motherboard.vice.com/read/the-fbi-let-its-license-for-hacking-teams-spyware-expire",
 title: "The FBI Let Its License for Hacking Team's Spyware Expire",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "July 17, 2015 // 12:17 PM EST" },
{ url: "http://motherboard.vice.com/read/leaked-emails-show-hacking-team-lied-to-its-rascal-customers",
 title: "Leaked Emails Show Hacking Team Lied to Its ‘Rascal’ Customers",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "July 14, 2015 // 02:50 PM EST" },
{ url: "http://motherboard.vice.com/read/the-fbi-wanted-to-use-hacking-teams-tools-on-a-tor-user",
 title: "The FBI Asked Hacking Team for Help Unmasking a Tor User",
 author: "JOSEPH COX",
 position: "CONTRIBUTOR",
 date: "July 14, 2015 // 12:00 PM EST" },
{ url: "http://motherboard.vice.com/read/hacking-team-reckless-and-vicious-crime-wont-stop-us",
 title: "Hacking Team: ‘Reckless and Vicious Crime’ Won’t Stop Us",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "July 13, 2015 // 11:34 AM EST" },
{ url: "http://motherboard.vice.com/read/hacking-teams-project-x-wants-to-spy-on-tor-users",
 title: "Hacking Team's 'Project X' Wants To Spy on Tor Users",
 author: "JOSEPH COX",
 position: "CONTRIBUTOR",
 date: "July 13, 2015 // 09:29 AM EST" },
{ url: "http://motherboard.vice.com/read/where-did-hacking-team-buy-its-hacks-three-accused-brokers-deny-involvement",
 title: "Where Did Hacking Team Buy Its Hacks? Three Accused Brokers Deny Wrongdoing",
 author: "JOSEPH COX",
 position: "CONTRIBUTOR",
 date: "July 13, 2015 // 08:25 AM EST" },
{ url: "http://motherboard.vice.com/read/hacking-team-gave-spyware-demos-to-police-agencies-across-the-nation",
 title: "Hacking Team Gave Spyware Demos to Police Agencies Across the Nation",
 author: "SHAWN MUSGRAVE",
 position: "CONTRIBUTOR",
 date: "July 29, 2015 // 11:20 AM EST" },
{ url: "http://motherboard.vice.com/read/here-is-a-government-surveillance-device-disguised-as-a-babys-car-seat",
 title: "Here Is a Government Surveillance Device Disguised as a Baby's Car Seat",
 author: "JOSHUA KOPSTEIN",
 position: "CONTRIBUTOR",
 date: "September 8, 2015 // 07:00 AM EST" },
{ url: "http://motherboard.vice.com/read/florida-cops-couldnt-survive-without-hacking-team-spy-tools",
 title: "Florida Cops Couldn't 'Survive' Without Hacking Team's Spy Tools ",
 author: "SHAWN MUSGRAVE",
 position: "CONTRIBUTOR",
 date: "September 21, 2015 // 01:15 PM EST" },
{ url: "http://motherboard.vice.com/read/everyone-and-their-mother-is-worried-about-getting-hacked",
 title: "Everyone and Their Mother Is Worried About Getting Hacked",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "October 13, 2015 // 11:51 AM EST" },
{ url: "http://motherboard.vice.com/read/hacking-team-is-back-with-a-bold-pitch-to-police",
 title: "Hacking Team Is Back with a Bold Pitch to Police",
 tags: ["essential"],
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "October 30, 2015 // 07:00 AM EST" },
{ url: "http://motherboard.vice.com/read/the-hacking-team-defectors",
 title: "The Hacking Team Defectors ",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "November 2, 2015 // 09:00 AM EST" },
{ url: "http://motherboard.vice.com/read/the-fbi-wont-confirm-or-deny-buying-hacking-team-spyware-even-though-it-did",
 title: "The FBI Won’t Confirm or Deny Buying Hacking Team Spyware, Even Though It Did",
 author: "LORENZO FRANCESCHI-BICCHIERAI",
 position: "STAFF WRITER",
 date: "December 9, 2015 // 11:35 AM EST" }];
